// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import DatetimeInputController from "./datetime_input_controller"
application.register("datetime-input", DatetimeInputController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import FormRangeController from "./form_range_controller"
application.register("form-range", FormRangeController)

import FormSubmitController from "./form_submit_controller"
application.register("form-submit", FormSubmitController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import MessageNotificationsSubscriptionController from "./message_notifications_subscription_controller"
application.register("message-notifications-subscription", MessageNotificationsSubscriptionController)

import NotificationsSubscriptionController from "./notifications_subscription_controller"
application.register("notifications-subscription", NotificationsSubscriptionController)

import RunSubscriptionController from "./run_subscription_controller"
application.register("run-subscription", RunSubscriptionController)

import SmallmapController from "./smallmap_controller"
application.register("smallmap", SmallmapController)

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)
